import React, { useEffect } from 'react';

const About = () => {
  // Page Title
  useEffect(() => {
    document.title = 'About';
    // eslint-disable-next-line
  }, []);
  return (
    <div className="row">
      <h4 className="center">About</h4>
      <div className="col s12 center">
        <p>
          This site serves as a personal tool for my Dungeons and Dragons games.
          It contains a few tools I found my self needing, as well as rules I
          needed to reference frequently.
        </p>
        <div className="divider" />
        <p>
          The Spell list and Condition page information are generated by using{' '}
          <a href="https://open5e.com/">Open5e's API</a>, and{' '}
          <a href="http://www.dnd5eapi.co/">D&D 5e API</a> which have both been
          great helps in developing this site.
        </p>
        <div className="divider" />
        <p>
          If you wish to contact me for any reason, please do so by emailing{' '}
          <a href="mailto:tyler@tylerpolito.info">here</a>.
        </p>
      </div>
    </div>
  );
};

export default About;
